version: '3'

services:
  api:
      container_name: dev_django
      hostname: django_api
      build:
          context: ./api/
          args:
              project_dir: "/workspace/"
      volumes: 
          - "./api:/workspace"
      environment:
          TZ: Asia/Tokyo
      tty: true
      privileged: true
      expose: 
        - "8000"
      networks: 
        app_net:
          ipv4_address: 192.168.56.10

  nginx:
      container_name: nginx
      hostname: nginx
      build: ./nginx/
      environment:
          TZ: Asia/Tokyo
      tty: true
      privileged: true
      ports: 
        - "80:80"
      networks: 
        app_net:
          ipv4_address: 192.168.56.20
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.56.0/24
          # gateway: 192.168.200.1